# Lista de Exercícios

## 1. Criando a base de dados

In [1]:
import pandas as pd
import numpy as np

dados = {
    "id": range(1, 21),
    "idade": [22, 35, 28, 45, 31, 19, 52, 41, 27, 33, 29, 38, 24, 46, 55, 30, 42, 26, 37, 200],
    "cidade": ["São Paulo", "Campinas", "Santos", "São Paulo", "Campinas",
               "Santos", "São Paulo", "São Paulo", "Campinas", "Santos",
               "São Paulo", "Campinas", "Santos", "São Paulo", "Campinas",
               "Santos", "São Paulo", "Campinas", "Santos", "São Paulo"],
    "renda": [2500, 4200, 3100, 6800, 3900, 2800, 7500, 6200, 3500, 4100,
              2900, 5300, 3200, 7100, 4500, 2700, 5900, 3600, 4800, 100000],
    "compras": [120, 250, 180, 430, 210, 150, 520, 390, 190, 280,
                160, 340, 200, 470, 310, 130, 380, 220, 290, 600],
    "quantidade": [2, 4, 3, 7, 3, 2, 8, 6, 2, 4,
                   2, 5, 3, 6, 4, 1, 5, 3, 4, 10]
}

df = pd.DataFrame(dados)
df

    id  idade     cidade   renda  compras  quantidade
0    1     22  São Paulo    2500      120           2
1    2     35   Campinas    4200      250           4
2    3     28     Santos    3100      180           3
3    4     45  São Paulo    6800      430           7
4    5     31   Campinas    3900      210           3
5    6     19     Santos    2800      150           2
6    7     52  São Paulo    7500      520           8
7    8     41  São Paulo    6200      390           6
8    9     27   Campinas    3500      190           2
9   10     33     Santos    4100      280           4
10  11     29  São Paulo    2900      160           2
11  12     38   Campinas    5300      340           5
12  13     24     Santos    3200      200           3
13  14     46  São Paulo    7100      470           6
14  15     55   Campinas    4500      310           4
15  16     30     Santos    2700      130           1
16  17     42  São Paulo    5900      380           5
17  18     26   Campinas    3600      220           3
18  19     37     Santos    4800      290           4
19  20    200  São Paulo  100000      600          10

## 2. Conhecendo os dados

Utilize as funções abaixo.

```python
df.head()
df.tail()
df.shape
df.columns
df.dtypes
df.info()
```

### Questões

1. Quantas linhas e colunas existem?
2. Quais são os nomes das colunas?
3. Qual é o tipo de cada coluna?
4. Mostre as 8 primeiras linhas.
5. Mostre as 3 últimas linhas.

In [ ]:
# 1
df.shape

(20, 6)

In [ ]:
# 2
df.columns

Index(['id', 'idade', 'cidade', 'renda', 'compras', 'quantidade'], dtype='str')

In [ ]:
# 3
df.dtypes

id            int64
idade         int64
cidade          str
renda         int64
compras       int64
quantidade    int64
dtype: object

In [ ]:
# 4
df.head(8)

   id  idade     cidade  renda  compras  quantidade
0   1     22  São Paulo   2500      120           2
1   2     35   Campinas   4200      250           4
2   3     28     Santos   3100      180           3
3   4     45  São Paulo   6800      430           7
4   5     31   Campinas   3900      210           3
5   6     19     Santos   2800      150           2
6   7     52  São Paulo   7500      520           8
7   8     41  São Paulo   6200      390           6

In [ ]:
# 5
df.tail(3)

    id  idade     cidade   renda  compras  quantidade
17  18     26   Campinas    3600      220           3
18  19     37     Santos    4800      290           4
19  20    200  São Paulo  100000      600          10

## 3. Selecionando dados

Utilize:

```python
df["idade"]
df[["idade", "renda"]]
df.loc[0]
df.iloc[0:5]
```

### Questões

1. Mostre somente a coluna `cidade`.
2. Mostre `idade`, `renda` e `compras`.
3. Mostre o registro de índice 10.
4. Mostre os registros de índice 5 a 10.
5. Compare `loc` e `iloc`.

In [ ]:
# 1
df["cidade"]

0     São Paulo
1      Campinas
2        Santos
3     São Paulo
4      Campinas
5        Santos
6     São Paulo
7     São Paulo
8      Campinas
9        Santos
10    São Paulo
11     Campinas
12       Santos
13    São Paulo
14     Campinas
15       Santos
16    São Paulo
17     Campinas
18       Santos
19    São Paulo
Name: cidade, dtype: str

In [ ]:
# 2
df[["idade", "renda", "compras"]]

    idade   renda  compras
0      22    2500      120
1      35    4200      250
2      28    3100      180
3      45    6800      430
4      31    3900      210
5      19    2800      150
6      52    7500      520
7      41    6200      390
8      27    3500      190
9      33    4100      280
10     29    2900      160
11     38    5300      340
12     24    3200      200
13     46    7100      470
14     55    4500      310
15     30    2700      130
16     42    5900      380
17     26    3600      220
18     37    4800      290
19    200  100000      600

In [ ]:
# 3
df.loc[10]

id                   11
idade                29
cidade        São Paulo
renda              2900
compras             160
quantidade            2
Name: 10, dtype: object

In [ ]:
# 4
df.loc[5:10]

    id  idade     cidade  renda  compras  quantidade
5    6     19     Santos   2800      150           2
6    7     52  São Paulo   7500      520           8
7    8     41  São Paulo   6200      390           6
8    9     27   Campinas   3500      190           2
9   10     33     Santos   4100      280           4
10  11     29  São Paulo   2900      160           2

## 4. Estatísticas

Utilize:

```python
df.describe()
df["idade"].mean()
df["idade"].median()
df["idade"].min()
df["idade"].max()
df["idade"].std()
```

### Questões

1. Qual é a idade média?
2. Qual é a idade mediana?
3. Qual é a maior renda?
4. Qual é a menor renda?
5. Qual é o valor médio das compras?
6. Qual variável numérica apresenta maior desvio-padrão?
7. Compare a média e a mediana de `renda`. O que você observa?

In [ ]:
# 1
df["idade"].mean()

np.float64(43.0)

In [ ]:
# 2
df["idade"].median()

np.float64(34.0)

In [ ]:
# 3
df["renda"].max()

np.int64(100000)

In [ ]:
# 4
df["renda"].min()

np.int64(2500)

In [ ]:
# 5
df["compras"].mean()

np.float64(291.0)

In [ ]:
# 6
df[['idade', 'renda', 'compras', 'quantidade']].std().idxmax()

'renda'

In [ ]:
# 7
print('Média:', df['renda'].mean())
print('Mediana:', df['renda'].median())

Média: 9230.0
Mediana: 4150.0

## 5. Valores únicos

Utilize:

```python
df["cidade"].unique()
df["cidade"].nunique()
df["cidade"].value_counts()
df["cidade"].value_counts(normalize=True)
```

### Questões

1. Quais cidades aparecem na base?
2. Quantas cidades existem?
3. Quantos clientes existem em cada cidade?
4. Qual cidade possui mais clientes?
5. Calcule a proporção de clientes de cada cidade.

In [ ]:
# 1
df["cidade"].unique()

<StringArray>
['São Paulo', 'Campinas', 'Santos']
Length: 3, dtype: str

In [ ]:
# 2
df["cidade"].nunique()

3

In [ ]:
# 3
df["cidade"].value_counts()

cidade
São Paulo    8
Campinas     6
Santos       6
Name: count, dtype: int64

In [ ]:
# 4
df["cidade"].value_counts().idxmax()

'São Paulo'

In [ ]:
# 5
df["cidade"].value_counts(normalize=True)

cidade
São Paulo    0.4
Campinas     0.3
Santos       0.3
Name: proportion, dtype: float64

## 6. Filtrando registros

Utilize:

```python
df[df["idade"] > 40]
df[df["renda"] > 5000]
df[(df["idade"] > 30) & (df["renda"] > 5000)]
df[df["cidade"] == "São Paulo"]
```

### Questões

1. Mostre clientes com idade superior a 40 anos.
2. Mostre clientes com renda superior a 5.000.
3. Mostre clientes de Campinas.
4. Mostre clientes com idade inferior a 30 anos e renda superior a R$ 3.000.
5. Quantos clientes possuem renda superior a 5.000?
6. Quantos clientes de São Paulo possuem compras superiores a 300?

In [ ]:
# 1
df[df["idade"] > 40]

    id  idade     cidade   renda  compras  quantidade
3    4     45  São Paulo    6800      430           7
6    7     52  São Paulo    7500      520           8
7    8     41  São Paulo    6200      390           6
13  14     46  São Paulo    7100      470           6
14  15     55   Campinas    4500      310           4
16  17     42  São Paulo    5900      380           5
19  20    200  São Paulo  100000      600          10

In [ ]:
# 2
df[df["renda"] > 5000]

    id  idade     cidade   renda  compras  quantidade
3    4     45  São Paulo    6800      430           7
6    7     52  São Paulo    7500      520           8
7    8     41  São Paulo    6200      390           6
11  12     38   Campinas    5300      340           5
13  14     46  São Paulo    7100      470           6
16  17     42  São Paulo    5900      380           5
19  20    200  São Paulo  100000      600          10

In [ ]:
# 3
df[df["cidade"] == "Campinas"]

    id  idade    cidade  renda  compras  quantidade
1    2     35  Campinas   4200      250           4
4    5     31  Campinas   3900      210           3
8    9     27  Campinas   3500      190           2
11  12     38  Campinas   5300      340           5
14  15     55  Campinas   4500      310           4
17  18     26  Campinas   3600      220           3

In [ ]:
# 4
df[(df["idade"] < 30) & (df["renda"] > 3000)]

    id  idade    cidade  renda  compras  quantidade
2    3     28    Santos   3100      180           3
8    9     27  Campinas   3500      190           2
12  13     24    Santos   3200      200           3
17  18     26  Campinas   3600      220           3

In [ ]:
# 5
(df["renda"] > 5000).sum()

np.int64(7)

In [ ]:
# 6
((df["cidade"] == "São Paulo") & (df["compras"] > 300)).sum()

np.int64(6)

## 7. Ordenando os dados

Utilize:

```python
df.sort_values("renda")
df.sort_values("renda", ascending=False)
df.sort_values(["cidade", "renda"])
```

### Questões

1. Ordene os clientes pela idade.
2. Ordene pela renda, da maior para a menor.
3. Mostre os cinco clientes com maior valor de compras.
4. Mostre os cinco clientes com menor renda.
5. Ordene os dados por cidade e, dentro de cada cidade, por renda decrescente.

In [ ]:
# 1
df.sort_values("idade")

    id  idade     cidade   renda  compras  quantidade
5    6     19     Santos    2800      150           2
0    1     22  São Paulo    2500      120           2
12  13     24     Santos    3200      200           3
17  18     26   Campinas    3600      220           3
8    9     27   Campinas    3500      190           2
2    3     28     Santos    3100      180           3
10  11     29  São Paulo    2900      160           2
15  16     30     Santos    2700      130           1
4    5     31   Campinas    3900      210           3
9   10     33     Santos    4100      280           4
1    2     35   Campinas    4200      250           4
18  19     37     Santos    4800      290           4
11  12     38   Campinas    5300      340           5
7    8     41  São Paulo    6200      390           6
16  17     42  São Paulo    5900      380           5
3    4     45  São Paulo    6800      430           7
13  14     46  São Paulo    7100      470           6
6    7     52  São Paulo    7500      520           8
14  15     55   Campinas    4500      310           4
19  20    200  São Paulo  100000      600          10

In [ ]:
# 2
df.sort_values("renda", ascending=False)

    id  idade     cidade   renda  compras  quantidade
19  20    200  São Paulo  100000      600          10
6    7     52  São Paulo    7500      520           8
13  14     46  São Paulo    7100      470           6
3    4     45  São Paulo    6800      430           7
7    8     41  São Paulo    6200      390           6
16  17     42  São Paulo    5900      380           5
11  12     38   Campinas    5300      340           5
18  19     37     Santos    4800      290           4
14  15     55   Campinas    4500      310           4
1    2     35   Campinas    4200      250           4
9   10     33     Santos    4100      280           4
4    5     31   Campinas    3900      210           3
17  18     26   Campinas    3600      220           3
8    9     27   Campinas    3500      190           2
12  13     24     Santos    3200      200           3
2    3     28     Santos    3100      180           3
10  11     29  São Paulo    2900      160           2
5    6     19     Santos    2800      150           2
15  16     30     Santos    2700      130           1
0    1     22  São Paulo    2500      120           2

In [ ]:
# 3
df.sort_values("compras", ascending=False).head(5)

    id  idade     cidade   renda  compras  quantidade
19  20    200  São Paulo  100000      600          10
6    7     52  São Paulo    7500      520           8
13  14     46  São Paulo    7100      470           6
3    4     45  São Paulo    6800      430           7
7    8     41  São Paulo    6200      390           6

In [ ]:
# 4
df.sort_values("renda").head(5)

    id  idade     cidade  renda  compras  quantidade
0    1     22  São Paulo   2500      120           2
15  16     30     Santos   2700      130           1
5    6     19     Santos   2800      150           2
10  11     29  São Paulo   2900      160           2
2    3     28     Santos   3100      180           3

In [ ]:
# 5
df.sort_values(["cidade", "renda"], ascending=[True, False])

    id  idade     cidade   renda  compras  quantidade
11  12     38   Campinas    5300      340           5
14  15     55   Campinas    4500      310           4
1    2     35   Campinas    4200      250           4
4    5     31   Campinas    3900      210           3
17  18     26   Campinas    3600      220           3
8    9     27   Campinas    3500      190           2
18  19     37     Santos    4800      290           4
9   10     33     Santos    4100      280           4
12  13     24     Santos    3200      200           3
2    3     28     Santos    3100      180           3
5    6     19     Santos    2800      150           2
15  16     30     Santos    2700      130           1
19  20    200  São Paulo  100000      600          10
6    7     52  São Paulo    7500      520           8
13  14     46  São Paulo    7100      470           6
3    4     45  São Paulo    6800      430           7
7    8     41  São Paulo    6200      390           6
16  17     42  São Paulo    5900      380           5
10  11     29  São Paulo    2900      160           2
0    1     22  São Paulo    2500      120           2

## 8. Amostragem

Utilize:

```python
df.sample(5)
df.sample(5, random_state=42)
df.sample(frac=0.25, random_state=42)
```

### Questões

1. Obtenha uma amostra aleatória de 5 clientes.
2. Execute a amostragem duas vezes sem `random_state`. Compare os resultados.
3. Execute duas vezes utilizando `random_state=42`. Compare os resultados.
4. Obtenha uma amostra correspondente a 25% dos dados.
5. Altere o `random_state` para 10 e compare com o resultado anterior.

In [ ]:
# 1
df.sample(5)

    id  idade     cidade   renda  compras  quantidade
19  20    200  São Paulo  100000      600          10
18  19     37     Santos    4800      290           4
4    5     31   Campinas    3900      210           3
5    6     19     Santos    2800      150           2
15  16     30     Santos    2700      130           1

In [ ]:
# 2
amostra1 = df.sample(5)
amostra2 = df.sample(5)

In [ ]:
# 3
amostra3 = df.sample(5, random_state=42)
amostra4 = df.sample(5, random_state=42)

In [ ]:
# 4
df.sample(frac=0.25, random_state=42)

    id  idade     cidade  renda  compras  quantidade
0    1     22  São Paulo   2500      120           2
17  18     26   Campinas   3600      220           3
15  16     30     Santos   2700      130           1
1    2     35   Campinas   4200      250           4
8    9     27   Campinas   3500      190           2

In [ ]:
# 5
df.sample(frac=0.25, random_state=10)

    id  idade     cidade  renda  compras  quantidade
7    8     41  São Paulo   6200      390           6
10  11     29  São Paulo   2900      160           2
5    6     19     Santos   2800      150           2
6    7     52  São Paulo   7500      520           8
3    4     45  São Paulo   6800      430           7

## 9. Dados faltantes

Nesta etapa, insira alguns valores faltantes.

Execute:

```python
df.loc[3, "renda"] = np.nan
df.loc[7, "idade"] = np.nan
df.loc[12, "cidade"] = np.nan
df.loc[15, "compras"] = np.nan
```

Utilize:

```python
df.isnull()
df.isnull().sum()
df.isnull().mean() * 100
```

### Questões

1. Quais colunas possuem valores faltantes?
2. Quantos valores faltantes existem em cada coluna?
3. Qual coluna possui maior percentual de valores faltantes?
4. Mostre somente os registros que possuem algum valor faltante.
5. Quantos registros possuem pelo menos um valor faltante?

In [ ]:
df.loc[3, "renda"] = np.nan
df.loc[7, "idade"] = np.nan
df.loc[12, "cidade"] = np.nan
df.loc[15, "compras"] = np.nan

In [ ]:
# 1
df.isnull().any()

id            False
idade          True
cidade         True
renda          True
compras        True
quantidade    False
dtype: bool

In [ ]:
# 2
df.isnull().sum()

id            0
idade         1
cidade        1
renda         1
compras       1
quantidade    0
dtype: int64

In [ ]:
# 3
df.isnull().mean().idxmax()

'idade'

In [ ]:
# 4
df[df.isnull().any(axis=1)]

    id  idade     cidade   renda  compras  quantidade
3    4   45.0  São Paulo     NaN    430.0           7
7    8    NaN  São Paulo  6200.0    390.0           6
12  13   24.0        NaN  3200.0    200.0           3
15  16   30.0     Santos  2700.0      NaN           1

In [ ]:
# 5
df.isnull().any(axis=1).sum()

np.int64(4)

## 10. Removendo dados faltantes

Utilize:

```python
df.dropna()
df.dropna(subset=["idade"])
```

### Questões

1. Crie um novo DataFrame removendo todos os registros com valores faltantes.
2. Quantos registros foram removidos?
3. Crie outro DataFrame removendo somente registros com `idade` faltante.
4. Compare os dois resultados.

In [ ]:
# 1
df_limpo = df.dropna()

In [ ]:
# 2
removidos = len(df) - len(df_limpo)
print(f'Registros removidos: {removidos}')

Registros removidos: 4

In [ ]:
# 3
df_sem_idade_nan = df.dropna(subset=["idade"])

In [ ]:
# 4
print('Tamanho df_limpo:', len(df_limpo))
print('Tamanho df_sem_idade_nan:', len(df_sem_idade_nan))

Tamanho df_limpo: 16
Tamanho df_sem_idade_nan: 19

## 11. Preenchendo dados faltantes

Utilize:

```python
df["idade"].fillna(df["idade"].median())
df["renda"].fillna(df["renda"].mean())
df["cidade"].fillna("Não informado")
```

### Questões

1. Preencha os valores faltantes de `idade` utilizando a mediana.
2. Preencha os valores faltantes de `renda` utilizando a média.
3. Preencha os valores faltantes de `compras` utilizando a mediana.
4. Preencha os valores faltantes de `cidade` com `"Não informado"`.
5. Verifique novamente `df.isnull().sum()`.
6. Compare `df.describe()` antes e depois do preenchimento.

In [ ]:
# 1
df["idade"] = df["idade"].fillna(df["idade"].median())

In [ ]:
# 2
df["renda"] = df["renda"].fillna(df["renda"].mean())

In [ ]:
# 3
df["compras"] = df["compras"].fillna(df["compras"].median())

In [ ]:
# 4
df["cidade"] = df["cidade"].fillna("Não informado")

In [ ]:
# 5
df.isnull().sum()

id            0
idade         0
cidade        0
renda         0
compras       0
quantidade    0
dtype: int64

In [ ]:
# 6
df.describe()

             id       idade          renda     compras  quantidade
count  20.00000   20.000000      20.000000   20.000000   20.000000
mean   10.50000   42.600000    9357.894737  298.500000    4.200000
std     5.91608   38.297176   21413.186193  131.640459    2.284962
min     1.00000   19.000000    2500.000000  120.000000    1.000000
25%     5.75000   27.750000    3175.000000  197.500000    2.750000
50%    10.50000   33.000000    4150.000000  280.000000    4.000000
75%    15.25000   42.750000    5975.000000  382.500000    5.250000
max    20.00000  200.000000  100000.000000  600.000000   10.000000

## 12. Identificando valores errôneos

Utilize:

```python
df["idade"].sort_values()
df[df["idade"] < 0]
df[df["idade"] > 100]
df[df["renda"] < 0]
df[df["quantidade"] <= 0]
```

### Questões

1. Existe alguma idade aparentemente inválida?
2. Existe alguma renda negativa?
3. Existe alguma quantidade inválida?
4. Identifique os registros que apresentam valores suspeitos.
5. Quantos registros apresentam algum desses problemas?

In [ ]:
# 1
df["idade"].sort_values()

5      19.0
0      22.0
12     24.0
17     26.0
8      27.0
2      28.0
10     29.0
15     30.0
4      31.0
9      33.0
7      33.0
1      35.0
18     37.0
11     38.0
16     42.0
3      45.0
13     46.0
6      52.0
14     55.0
19    200.0
Name: idade, dtype: float64

In [ ]:
# 2
df[df["renda"] < 0]

Empty DataFrame
Columns: [id, idade, cidade, renda, compras, quantidade]
Index: []

In [ ]:
# 3
df[df["quantidade"] <= 0]

Empty DataFrame
Columns: [id, idade, cidade, renda, compras, quantidade]
Index: []

In [ ]:
# 4
df[df["idade"] > 100]

    id  idade     cidade     renda  compras  quantidade
19  20  200.0  São Paulo  100000.0    600.0          10

In [ ]:
# 5
(df["idade"] > 100).sum()

np.int64(1)

## 13. Corrigindo valores errôneos

Utilize:

```python
df.loc[df["idade"] > 100, "idade"] = np.nan
df["idade"] = df["idade"].fillna(df["idade"].median())
```

### Questões

1. Substitua a idade inválida por `NaN`.
2. Preencha o valor utilizando a mediana.
3. Verifique novamente o valor máximo da idade.
4. Verifique novamente as estatísticas da variável.

In [ ]:
# 1
df.loc[df["idade"] > 100, "idade"] = np.nan

In [ ]:
# 2
df["idade"] = df["idade"].fillna(df["idade"].median())

In [ ]:
# 3
df["idade"].max()

np.float64(55.0)

In [ ]:
# 4
df["idade"].describe()

count    20.000000
mean     34.250000
std       9.705533
min      19.000000
25%      27.750000
50%      33.000000
75%      39.000000
max      55.000000
Name: idade, dtype: float64

## 14. Identificando outliers

Utilize:

```python
Q1 = df["renda"].quantile(0.25)
Q3 = df["renda"].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

outliers = df[
    (df["renda"] < limite_inferior) |
    (df["renda"] > limite_superior)
]

outliers
```

### Questões

1. Calcule Q1, Q3 e IQR da renda.
2. Calcule os limites inferior e superior.
3. Quais registros são considerados outliers?
4. Quantos outliers foram encontrados?
5. Repita o procedimento para `compras`.
6. Altere `1.5` para `2`. O número de outliers mudou?

In [ ]:
# 1
Q1 = df["renda"].quantile(0.25)
Q3 = df["renda"].quantile(0.75)
IQR = Q3 - Q1
print('IQR da renda:', IQR)

IQR da renda: 2800.0

In [ ]:
# 2
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR
print('Lim inferior:', limite_inferior, '| Lim superior:', limite_superior)

Lim inferior: -1025.0 | Lim superior: 10175.0

In [ ]:
# 3
outliers = df[(df["renda"] < limite_inferior) | (df["renda"] > limite_superior)]
outliers

    id  idade     cidade     renda  compras  quantidade
19  20   33.0  São Paulo  100000.0    600.0          10

In [ ]:
# 4
len(outliers)

1

In [ ]:
# 5
Q1_c = df["compras"].quantile(0.25)
Q3_c = df["compras"].quantile(0.75)
IQR_c = Q3_c - Q1_c
lim_inf_c = Q1_c - 1.5 * IQR_c
lim_sup_c = Q3_c + 1.5 * IQR_c
outliers_compras = df[(df["compras"] < lim_inf_c) | (df["compras"] > lim_sup_c)]
len(outliers_compras)

0

In [ ]:
# 6
lim_inf_2 = Q1 - 2 * IQR
lim_sup_2 = Q3 + 2 * IQR
outliers_2 = df[(df["renda"] < lim_inf_2) | (df["renda"] > lim_sup_2)]
print('Com 1.5:', len(outliers), ' | Com 2.0:', len(outliers_2))

Com 1.5: 1  | Com 2.0: 1

## 15. Tratando outliers

Utilize:

```python
df_sem_outliers = df[
    (df["renda"] >= limite_inferior) &
    (df["renda"] <= limite_superior)
]
```

Também podemos utilizar:

```python
df["renda"].clip(lower=limite_inferior, upper=limite_superior)
```

### Questões

1. Crie uma versão da base sem os outliers de renda.
2. Compare o número de registros antes e depois.
3. Compare `df["renda"].describe()` com `df_sem_outliers["renda"].describe()`.
4. Crie uma versão utilizando `clip()`.
5. Compare os resultados obtidos pelas duas técnicas.

In [ ]:
# 1
df_sem_outliers = df[(df["renda"] >= limite_inferior) & (df["renda"] <= limite_superior)]

In [ ]:
# 2
print('Antes:', len(df), ' | Depois:', len(df_sem_outliers))

Antes: 20  | Depois: 19

In [ ]:
# 3
print(df["renda"].describe())
print(df_sem_outliers["renda"].describe())

count        20.000000
mean       9357.894737
std       21413.186193
min        2500.000000
25%        3175.000000
50%        4150.000000
75%        5975.000000
max      100000.000000
Name: renda, dtype: float64
count      19.000000
mean     4587.257618
std      1879.043452
min      2500.000000
25%      3150.000000
50%      4100.000000
75%      5600.000000
max      9357.894737
Name: renda, dtype: float64

In [ ]:
# 4
df_clip = df.copy()
df_clip["renda"] = df_clip["renda"].clip(lower=limite_inferior, upper=limite_superior)

## 16. Agrupando os dados

Utilize:

```python
df.groupby("cidade")["renda"].mean()
df.groupby("cidade")["compras"].mean()
df.groupby("cidade")["renda"].agg(["mean", "median", "min", "max"])
```

### Questões

1. Calcule a renda média por cidade.
2. Calcule a média de compras por cidade.
3. Calcule média, mediana, mínimo e máximo da renda por cidade.
4. Qual cidade possui a maior renda média?
5. Qual cidade possui a maior média de compras?

In [ ]:
# 1
df.groupby("cidade")["renda"].mean()

cidade
Campinas          4166.666667
Não informado     3200.000000
Santos            3500.000000
São Paulo        17682.236842
Name: renda, dtype: float64

In [ ]:
# 2
df.groupby("cidade")["compras"].mean()

cidade
Campinas         253.333333
Não informado    200.000000
Santos           236.000000
São Paulo        383.750000
Name: compras, dtype: float64

In [ ]:
# 3
df.groupby("cidade")["renda"].agg(["mean", "median", "min", "max"])

                       mean  median     min       max
cidade
Campinas        4166.666667  4050.0  3500.0    5300.0
Não informado   3200.000000  3200.0  3200.0    3200.0
Santos          3500.000000  3100.0  2700.0    4800.0
São Paulo      17682.236842  6650.0  2500.0  100000.0

In [ ]:
# 4
df.groupby("cidade")["renda"].mean().idxmax()

'São Paulo'

In [ ]:
# 5
df.groupby("cidade")["compras"].mean().idxmax()

'São Paulo'